### PR TITLE
Update cargo, lasso and string interner + many minor improvements

### PR DESCRIPTION
**Pull request by Robbepop**
This PR also introduces several improvements mainly for usage of the scripts.

- Added Cargo aliases for `sample` and `report`.
- Made python script optionally `plot.py` executable.
- Add command `interner_string` to use the `StringBackend` of the `string-interner`.
- Add command `Interner_bucket` to explicitly test the `BucketBackend` of the  `string-interner`.
- Updated and improved `README`.
- Update `Cargo.lock`.
- Add sample for `strena` without `with_capacity` to make comparison more fair.

I am not sure how you did this last graph in your blog post with overlapping `lasso` and `string-interner` performance but I'd love to have this in this script.

## Rendered Usage

2020-07-15-164713_899x711_scrot

### Strena::with_capacity

strena-with-capacity-plot

### Strena::new
strena-new-plot

### StringInterner using BucketBackend

interner-bucket-plot

### StringInterner using StringBackend

interner-string-plot

### Lasso

lasso-plot

### CODE REVIEW

**Comment by Robbepop** [comment]
Anything i have to change or improve in oder for this to merge?

**Comment by CAD97** [comment]
Nothing specific, this has just been lower on my priority list 😅

**Comment by Robbepop** [comment]
Any chance this gets merged? 😅

**Comment by Robbepop** [comment]
I just updated to newest `cargo`, `string-interner` (version 0.12 -> 0.14) and `lasso` (version 0.3 -> 0.6) versions.
Lasso has not changed with respect to memory consumption, however, the `string_interner` has received a new backend (`BufferBackend`) which was optimized for memory consumption. See below:

interner-buffer-plot

Comparison with `lasso` version 0.6:

lasso-plot

Comparison with `strena`:

strena-new-plot

**Comment by dralley** [comment]
@CAD97 I too would also love to see an update

**Comment by Robbepop** [comment]
This PR has been open for 3 years without feedback. So I am closing this now.

**Pull request closed without merging**
